image: node:16-buster  # Use a Docker image with Node.js

stages:
  - build
  - test
  - validate
  - deploy

variables:
  DEV_ORG_ALIAS: "devMigration"   # Developer Org
  PROD_ORG_ALIAS: "dataMigration"  # Production Org
  SFDC_CONSUMER_KEY: "3MVG931doue2KUvxprXUl7FzLhoXUGfdSyvNWYbweME3DR2QP7Wzd53TUXH_DKm_qHmugmrsaoe1WRLFdwZaQ"
  SFDC_USERNAME: "hai@ovalo4BoondLab.com"
  SFDC_CONSUMER_KEY_PROD: "3MVG9suI4ZYS8sz4Pt.Nmcin8aiPw5sQjV.isOHLfMdhpM2DzCWydsoKW3cwVnVpyYA46XtMJj2ULQEKZleE0"
  SFDC_PROD_USERNAME: "hai@ovalo2024.fr"

before_script:
  - npm install --global sfdx-cli        # Install Salesforce CLI
  - sfdx force:auth:jwt:grant --clientid $SFDC_CONSUMER_KEY --jwtkeyfile ./server.key --username $SFDC_USERNAME --instanceurl https://test.salesforce.com --setdefaultusername -a $DEV_ORG_ALIAS

  - sfdx force:source:deploy -u $DEV_ORG_ALIAS -p force-app  # Authenticate to the Prod Org
  - sfdx force:auth:jwt:grant --clientid $SFDC_CONSUMER_KEY_PROD --jwtkeyfile ./server.key --username $SFDC_PROD_USERNAME --instanceurl https://login.salesforce.com --setdefaultusername -a $PROD_ORG_ALIAS


build:
  stage: build
  script:
    - echo "Building the Salesforce project..."
    - sfdx force:source:deploy -u $DEV_ORG_ALIAS --manifest manifest/package.xml  # Push changes to Dev Org

test:
  stage: test
  script:
    - echo "Running Salesforce unit tests..."
    - sfdx force:apex:test:run -u $DEV_ORG_ALIAS --resultformat human --wait 10
    - sfdx force:source:retrieve -u $DEV_ORG_ALIAS -p force-app  # Retrieve latest changes from Dev Org

validate:
  stage: validate
  script:
    - echo "Validating the deployment to production..."
    - sfdx force:source:deploy -u $PROD_ORG_ALIAS --checkonly --manifest manifest/package.xml  # Validate without committing changes
  only:
    - merge_requests
deploy:
  stage: deploy
  script:
    - echo "Deploying to Production Org..."
    - sfdx force:source:deploy -u $PROD_ORG_ALIAS -p force-app  # Deploy to Production Org
  only:
    - main  # Run only on the main branch
