image: node:16-buster  # Use a Docker image with Node.js

stages:
  - build
  - test
  - deploy

variables:
  DEV_ORG_ALIAS: "devMigration"   # Developer Org
  PROD_ORG_ALIAS: "dataMigration"  # Production Org
  SFDC_CONSUMER_KEY: "3MVG931doue2KUvxprXUl7FzLhoXUGfdSyvNWYbweME3DR2QP7Wzd53TUXH_DKm_qHmugmrsaoe1WRLFdwZaQ"
  SFDC_USERNAME: "hai@ovalo4BoondLab.com"

before_script:
  - npm install --global sfdx-cli        # Install Salesforce CLI
  - sfdx force:auth:jwt:grant --clientid $SFDC_CONSUMER_KEY --jwtkeyfile ./server.key --username $SFDC_USERNAME --instanceurl https://test.salesforce.com --setdefaultusername -a $DEV_ORG_ALIAS

  - sfdx force:auth:login -d -u $PROD_ORG_ALIAS  # Authenticate to the Prod Org

build:
  stage: build
  script:
    - echo "Building the Salesforce project..."
    - sfdx force:source:push -u $DEV_ORG_ALIAS  # Push changes to Dev Org

test:
  stage: test
  script:
    - echo "Running Salesforce unit tests..."
    - sfdx force:apex:test:run -u $DEV_ORG_ALIAS --resultformat human --wait 10
    - sfdx force:source:retrieve -u $DEV_ORG_ALIAS -p force-app  # Retrieve latest changes from Dev Org

deploy:
  stage: deploy
  script:
    - echo "Deploying to Production Org..."
    - sfdx force:source:deploy -u $PROD_ORG_ALIAS -p force-app  # Deploy to Production Org
  only:
    - main  # Run only on the main branch
