stages:
  - build
  - test
  - deploy

variables:
  DEV_ORG_ALIAS: "devMigration"  # Developer Org for Testing
  PROD_ORG_ALIAS: "myIntegAlias" # Production Org for Deployment

build:
  stage: build
  script:
    - echo "Building the Salesforce project..."
    - sfdx force:source:push -u $DEV_ORG_ALIAS

test:
  stage: test
  script:
    - echo "Running Salesforce unit tests with coverage..."
    - sfdx force:apex:test:run -u $DEV_ORG_ALIAS --resultformat human --wait 10 --codecoverage
    - sfdx force:source:retrieve -u $DEV_ORG_ALIAS -p force-app

deploy:
  stage: deploy
  script:
    - echo "Validating Deployment to Integ Org..."
    - sfdx force:source:deploy -u $PROD_ORG_ALIAS -p force-app --checkonly
    - sfdx force:source:deploy -u $PROD_ORG_ALIAS -p force-app  # Actual deployment if validation passes
  only:
    - uat-branch
