name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  auth:
    name: Authenticate Orgs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install --global sfdx-cli

      - name: Authenticate Dev Org
        run: |
          echo "${{ secrets.SFDC_SERVER_KEY }}" > server.key
          sfdx force:auth:jwt:grant --clientid ${{ secrets.SFDC_CONSUMER_KEY }} --jwtkeyfile ./server.key --username ${{ secrets.SFDC_USERNAME }} --instanceurl https://test.salesforce.com --setdefaultusername -a devMigration

      - name: Authenticate Prod Org
        run: |
          echo "${{ secrets.SFDC_SERVER_KEY }}" > server.key
          sfdx force:auth:jwt:grant --clientid ${{ secrets.SFDC_CONSUMER_KEY_PROD }} --jwtkeyfile ./server.key --username ${{ secrets.SFDC_PROD_USERNAME }} --instanceurl https://login.salesforce.com --setdefaultusername -a dataMigration

  build:
    name: Build and Deploy to Dev
    needs: auth
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev Org
        run: sfdx force:source:deploy -u devMigration --manifest manifest/package.xml

  test:
    name: Run Apex Tests
    needs
